version: '3'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=pismobank
      - POSTGRES_PASSWORD=pismobank
    expose:
      - 5432
    ports:
        - 5432:5432
  app:
    image: 'pismobank:latest'
    build:
      context: .
    container_name: pismobank
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/pismobank
      - DATABASE_USER=pismobank
      - DATABASE_PASSWORD=pismobank

